#!/bin/bash
###############################################################################
# Author: jayanatl@gmail.com
# Description: /etc/hosts file generator
# Date: 2019-07-04
###############################################################################

# Variables
baseip=${1:-192.168.100}
domain=${2:-example.com}
hosts="/etc/hosts1"
header="Generated by setup script"

# Backup and cleanup
sed -i.$(date +%s) "/${header}/,/END ${header}/d" ${hosts} || exit 127

# Add header
cat << EOF >> ${hosts}

# ${header}
#   Baseip: ${baseip}
#   Domain: ${domain}
EOF

# Add content
for ((i=1; i<250; ++i)); do
    echo ${baseip}.${i} node${i}.${domain} node${i} >> ${hosts}
done

# Static entries
cat << EOF >> ${hosts}
${baseip}.250 master.${domain} master
${baseip}.251 vmhost.${domain} vmhost
${baseip}.254 router.${domain} router nat
# END ${header}
EOF